import argparse
import sys
from pathlib import Path

import csv

parser = argparse.ArgumentParser(description='Script to convert CSV generated by ExaHyPE2 executions into plots')
parser.add_argument("--f",               dest="name",      type=str,   required=True,  help="Name of the file to be checked, does not need to contain '.csv'" )
parser.add_argument("--s",            dest="skip",          type=int, default=1,   help="only take every second row" )
args = parser.parse_args()

with open(args.name, newline="", encoding="utf-8") as f:
    csvData= list(csv.reader(f, delimiter=','))

output = []
output.append(csvData[0])
csvData = csvData[1:]

for i in range(len(csvData)):
    if i % args.skip != 0:
        continue
    output.append(csvData[i])

name = args.name.split("tracer")[0] + "compr" + str(args.skip) + "_tracer" + args.name.split("tracer")[1]

with open(name, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f,delimiter=",")
    writer.writerows(output)