import argparse

import csv

change_map = { # tpv16
    "0":"26.0",
    "1":"26.0",
    "2":"26.0",
    "3":"20.2",
    "4":"20.2",
    "5":"20.2",
    "6":"19.8",
    "7":"19.8",
    "8":"19.8",
    "9":"14.0",
    "10":"14.0",
    "11":"14.0",
    "12":"19.99",
    "13":"19.99",
    "14":"19.99",
    "15":"19.99",
    "16":"19.99",
    "17":"19.99",
    "18":"20.01",
    "19":"20.01",
    "20":"20.01",
    "21":"20.01",
    "22":"20.01",
    "23":"20.01",
    "24":"",
    "25":"",
    "26":""
}

change_map = { # tpv9
    "0":"17.0",
    "1":"18.0",
    "2":"19.0",
    "3":"21.0",
    "4":"22.0",
    "5":"23.0",
    "6":"17.0",
    "7":"23.0",
    "8":"19.0",
    "9":"19.5",
    "10":"20.5",
    "11":"21.0",
    "12":"17.0",
    "13":"23.0",
    "14":"19.99",
    "15":"19.99",
    "16":"19.99",
    "17":"19.99",
    "18":"19.99",
    "19":"19.99",
    "20":"19.99",
    "21":"19.99",
    "22":"20.01",
    "23":"20.01",
    "24":"20.01",
    "25":"20.01",
    "26":"20.01",
    "27":"20.01",
    "28":"20.01",
    "29":"20.01"
}

parser = argparse.ArgumentParser(description='Script to convert CSV generated by ExaHyPE2 executions into plots')
parser.add_argument("--f",               dest="file_name",      type=str,   required=True,  help="Name of the file to be checked, does not need to contain '.csv'" )
args = parser.parse_args()

with open(args.file_name, newline="", encoding="utf-8") as f:
    csvData= list(csv.reader(f, delimiter=','))

for entry in csvData:
    if entry[0] in change_map.keys():
        entry[3] = " " + change_map[entry[0]]

with open(args.file_name, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f,delimiter=",")
    writer.writerows(csvData)