import argparse

import csv

parser = argparse.ArgumentParser(description='Script to convert CSV generated by ExaHyPE2 executions into plots')
parser.add_argument("--f",               dest="file_name",      type=str,   required=True,  help="Name of the file to be checked, does not need to contain '.csv'" )
parser.add_argument("--i",               dest="data_info",      type=str,   required=True,  help="Name of the file to be checked, does not need to contain '.csv'" )
parser.add_argument("--t",               dest="tracer",       type=int,   required=True,  help="ID of tracer")
parser.add_argument("--d",               dest="data_id",       type=int,   required=True,  help="Data column to keep")
parser.add_argument("--t2",              dest="tracer2",       type=int,   default=-1,  help="ID of 2nd tracer, if sub is needed")
parser.add_argument("--o",               dest="offset",       type=float,   default=0,  help="offset to give the data in all data entries")
args = parser.parse_args()

with open(args.file_name, newline="", encoding="utf-8") as f:
    csvData= list(csv.reader(f, delimiter=','))[:]
    while csvData[0][0].startswith("#"):
        csvData = csvData[1:]
    
    csvData = csvData[1:]

coords = []

for entry in csvData:
    if int(entry[0]) == int(args.tracer):
        coords.append(str(int(float(entry[3]))))
        coords.append(str(int(float(entry[4]))))
        coords.append(str(int(float(entry[5]))))
        break

output = []

if args.tracer2 == -1:
    for entry in csvData:
        if int(entry[0]) == int(args.tracer):
            output.append([float(entry[2]),float(entry[6 + args.data_id]) + args.offset])
else:
    tracer1 = []
    tracer2 = []
    for entry in csvData:
        if int(entry[0]) == int(args.tracer):
            tracer1.append(entry)
        elif int(entry[0]) == int(args.tracer2):
            tracer2.append(entry)
    
    tracer1 = sorted(tracer1[:max(len(tracer1),len(tracer2))])
    tracer2 = sorted(tracer2[:max(len(tracer1),len(tracer2))])

    for t1,t2 in zip(tracer1,tracer2):
        output.append([float(t1[2]),str(float(t1[6 + args.data_id]) - float(t2[6 + args.data_id]) + args.offset)])

write = [["t","data"]]
write.extend(sorted(output))

with open(args.file_name[:-4] + "_tracer" + str(args.tracer) + "_" + coords[0] + "_" + coords[1] + "_" + coords[2] + "_" + args.data_info + ".csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f,delimiter=",")
    writer.writerows(write)