from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import time
import sys
import argparse

# The URL of the page with the form
STRIKE_URL = "https://strike.scec.org/cvws/cgi-bin/cvws.cgi"

parser = argparse.ArgumentParser(description='Script to convert CSV generated by ExaHyPE2 executions into plots')
parser.add_argument("--s",               dest="scenario",      type=str,   required=True,  help="Name of the scenario you want to get a solution for." )
parser.add_argument("--r",               dest="reference",      type=str,   required=True,  help="Name of the reference solution you want to generate" )
args = parser.parse_args()
scenario_name = args.scenario
reference_name = args.reference

PUB_AREA_CODE = "G0012"
SCENARIOS_CODE = "G1045"
SOLUTIONS_CODE = "G1047"
RAW_DATA_CODE = "G1059"

# Get all submit button names that start with the given code
def get_all_possible_options(option_code):
    option_names = []
    curIndex = -1
    rest_of_page = driver.page_source
    nextIndex = rest_of_page[1:].find(option_code)
    while nextIndex != -1:
        curIndex = nextIndex+1
        rest_of_page = rest_of_page[curIndex:]
        until = rest_of_page.find('"')
        new_option = rest_of_page[len(option_code):until]
        #print(new_option)
        option_names.append(new_option)

        nextIndex = rest_of_page[1:].find(option_code)

    return option_names

#format should be: tracer_id 0 t x y z data
#input format of curline is: t data
def format_data_line(tracer_id, tracer_pos, cur_line_data: str):
    # TODO: Format properly
    line = str(tracer_id)+",0"
    data_entries = cur_line_data.strip().split(" ")
    
    line += "," + data_entries[0].strip()
    
    for coord in tracer_pos:
        line += "," + str(coord)
    for i in range(1,len(data_entries)):
        if data_entries[i] == "":
            continue
        line += "," + data_entries[i].strip()

    return line + "\n"

# helper that converts '-xxx' or 'xxx' into a number -xx.x or xx.x 
def get_single_coordinate(tracer_name):
    if tracer_name.startswith("-"):
        return - float(tracer_name[1:3] + "." + tracer_name[3])
    else:
        return float(tracer_name[:2] + "." + tracer_name[2])

# converts a tracer_name that is either structured as 'faultst-045dp000' or 'body030st-120dp075' to the corresponding tracer position
def get_tracer_pos(tracer_name:str):
    x = 0.0
    if tracer_name.startswith("fault"):
        x = 20.0
        tracer_name = tracer_name[5:]
    elif tracer_name.startswith("body"):
        tracer_name = tracer_name[4:]
        x = get_single_coordinate(tracer_name)
        tracer_name = tracer_name[3+(1 if x < 0.0 else 0):]
        x += 20.0
    
    #skip 'st'
    tracer_name = tracer_name[2:]
    z = get_single_coordinate(tracer_name)
    tracer_name = tracer_name[3+(1 if z < 0.0 else 0):]
    z += 20.0

    #skip 'dp'
    tracer_name = tracer_name[2:]
    y = get_single_coordinate(tracer_name)

    return (x,y,z)



# start browser
opts = Options()
opts.add_argument("--headless=new")   # don't show browser
driver = webdriver.Chrome(options=opts)  # if this line crashes, you don't have the chromedriver installed / available

print("Searching for scenario...")
driver.get(STRIKE_URL) 
# Click on 'Public Area' Button
pub_area_button = driver.find_element(By.NAME, PUB_AREA_CODE)
pub_area_button.click()

# give the browser a moment to load
time.sleep(1)
# check if the scenario exists, and if so load the scenario page
try:
    scenario_button = driver.find_element(By.NAME,SCENARIOS_CODE + scenario_name)
    scenario_button.click()
    time.sleep(1)
except:
    print("Couldn't find scenario '" + scenario_name + "'.")
    print("Available scenarios are: " + str(get_all_possible_options(SCENARIOS_CODE)))
    print("Exiting now.")
    driver.quit()
    sys.exit()

# check if the reference solution exists, and if so load the solution
try:
    ref_sol_button = driver.find_element(By.NAME,SOLUTIONS_CODE + reference_name)
    ref_sol_button.click()
    time.sleep(1)
except:
    print("Couldn't find reference solution '" + reference_name + "' for scenario '" + scenario_name + "'.")
    print("Available reference solutions are: " + str(get_all_possible_options(SOLUTIONS_CODE)))
    print("Exiting now.")
    driver.quit()
    sys.exit()

# get all tracer names
print("Initializing variables...")
tracer_names = get_all_possible_options(RAW_DATA_CODE)
# print(tracer_names)

# Set the variable names of the data and put them as a comment in the first two lines of the csv file
got_on_fault_param_names = False
got_off_fault_param_names = False
first_line = "# data_on_fault = "
second_line = "# data_off_fault = "
for tracer in tracer_names:
    if not got_on_fault_param_names and tracer.startswith("fault"):
        got_on_fault_param_names = True
        raw_data_button = driver.find_element(By.NAME,RAW_DATA_CODE + tracer)
        raw_data_button.click()
        time.sleep(1)
        raw_data = driver.find_element(By.TAG_NAME, "pre").text
        first_line += raw_data[raw_data.find("\nt ")+2:].split("\n")[0] + "\n"
        driver.back()
    if not got_off_fault_param_names and tracer.startswith("body"):
        got_off_fault_param_names = True
        raw_data_button = driver.find_element(By.NAME,RAW_DATA_CODE + tracer)
        raw_data_button.click()
        time.sleep(1)
        raw_data = driver.find_element(By.TAG_NAME, "pre").text
        second_line += raw_data[raw_data.find("\nt ")+2:].split("\n")[0] + "\n"
        driver.back()


with open(scenario_name.upper() + "_ref_" + reference_name + ".csv", "w") as output_file:
    # initialize csv file
    output_file.write(first_line)
    output_file.write(second_line)
    output_file.write("number(0), number(1), t, x(0), x(1), x(2), data \n")
    print("Initialized everything correctly, starting to get data now...")
    print("0% done")

    # get the data of every tracer, format it, and add it to the csv file 
    for i in range(0,len(tracer_names)):
        tracer_pos = get_tracer_pos(tracer_names[i])

        # go to raw data page of tracer
        raw_data_button = driver.find_element(By.NAME,RAW_DATA_CODE + tracer_names[i])
        raw_data_button.click()
        time.sleep(1)
        
        # retrieve tracer data
        raw_data = driver.find_element(By.TAG_NAME, "pre").text
        raw_data_lines = raw_data[raw_data.find("\nt ")+1:].split("\n")

        for j in range(1,len(raw_data_lines)):
            if raw_data_lines[j].startswith("#"):
                continue
            output_file.write(format_data_line(i,tracer_pos,raw_data_lines[j]))
        
        print(str(int((i+1)/len(tracer_names) * 100)) + "% done")
        driver.back()
        time.sleep(0.25)


print("Saved solution as: '" + scenario_name.upper() + "_ref_" + reference_name + ".csv'")
driver.quit()
